name: Upload Python Package

on:
  push:
    branches:
      - master
    paths:
      - "fgo_api_types/**"
      - "app/schemas/*.py"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Default
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Build package
        run: |
          cp app/schemas/*.py fgo_api_types/fgo_api_types/
          cd fgo_api_types
          poetry version $(date -u +"%Y.%m.%d.%H.%M.%S")
          poetry build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: fgo_api_types/dist/*.whl
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: fgo_api_types/dist/
          skip-existing: true
          verbose: true
          print-hash: true
