name: Update translation files

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update translation files
        run: |
          git clone https://git.atlasacademy.io/atlasacademy/fgo-game-data.git --branch JP --depth 1 /tmp/fgo-game-data-jp
          git clone https://git.atlasacademy.io/atlasacademy/fgo-game-data.git --branch NA --depth 1 /tmp/fgo-game-data-na
          python ./scripts/update_ce_translation.py --jp-master /tmp/fgo-game-data-jp/master --na-master /tmp/fgo-game-data-na/master
      - name: Commit translation update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add app/data/mappings
          git commit -m "Updated translations" || echo "Nothing to commit"
          git push
